version: '3.3'

services:
  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./postgis_data:/var/lib/postgresql/data

  schema_import:
    image: openjdk:11
    volumes:
      - ./jars/ili2pg-4.4.4/:/app/ili2pg-4.4.4/
      - ./jars/RIC/:/app/RIC/
    command: "java -jar /app/ili2pg-4.4.4/ili2pg-4.4.4.jar --schemaimport --dbhost postgis --dbport 5432 --dbusr postgres --dbpwd admin --dbdatabase db --dbschema postgres --setupPgExt --coalesceCatalogueRef --createEnumTabs --createNumChecks --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createUnique --createGeomIdx --createFk --createFkIdx --createMetaInfo --expandMultilingual --createTypeConstraint --createEnumTabsWithId --createTidCol --smart2Inheritance --strokeArcs --defaultSrsCode 9377 --preScript /app/RIC/5_RIC_dev/insert_ctm12_pg.sql --modeldir /app/RIC/ --models Modelo_Aplicacion_LADMCOL_RIC_V0_1"
    depends_on: 
      - postgis

  # data_import:
  #   image: openjdk:11
  #   volumes:
  #     - ./jars/ili2pg-4.4.4/:/app/
  #     - ./IGAC.xtf:/app/IGAC.xtf
  #   #command: "java -jar /app/ili2pg-4.4.4.jar --import --importTid --dbhost postgis --dbport 5432 --dbusr postgres --dbpwd admin --dbdatabase db --dbschema postgres --coalesceCatalogueRef --createEnumTabs --createNumChecks --coalesceMultiSurface --coalesceMultiLine --coalesceMultiPoint --coalesceArray --beautifyEnumDispName --createUnique --createGeomIdx --createFk --createFkIdx --createMetaInfo --expandMultilingual --createTypeConstraint --createEnumTabsWithId --createTidCol --smart2Inheritance --strokeArcs --defaultSrsCode 9377 --modeldir /app --models Modelo_Aplicacion_LADMCOL_RIC_V0_1 /app/IGAC_25372.xtf"
  #   depends_on: 
  #     - postgis

  # data_export:
  #   image: openjdk:11
  #   volumes:
  #     - ./jars/ili2pg-4.4.4/:/app/
  #     - ./delete.xtf:/app/delete.xtf
  #     - ./errores.txt:/app/errores.txt
  #   #command: "java -jar /app/ili2pg-4.4.4.jar --dbhost postgis --dbport 5432 --dbusr postgres --dbpwd admin --dbdatabase db --dbschema postgres --export --exportTid --modeldir /app --models Modelo_Aplicacion_LADMCOL_RIC_V0_1 --log /app/errores.txt /app/delete.xtf"
  #   depends_on: 
  #     - postgis


